name: Java PR Testing Pipeline

on:
  pull_request:
    branches: [ "main", "master" ]

jobs:
  compile:
    name: Compile project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Compile main source code
        run: mvn -B clean compile

  tests:
    name: Run custom automated tests
    runs-on: ubuntu-latest
    needs: compile
    continue-on-error: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Compile test source code
        run: mvn -B test-compile

      - name: Run custom TestRunner
        run: java -cp target/test-classes com.checkerstactics.TestRunner